name: Get and cache dependencies
description: 'Get the dependencies and cache them.'
runs:
  using: composite
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: react_demo/node_modules
        key: actions-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd react_demo
        npm ci
