name: Exercise output event information
on: workflow_dispatch
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output Event context
        run: |
          echo "Event Name: ${{github.event_name}}"
          echo "Event Object JSON: ${{tojson (github.event)}}"
          