name: Conditional with reusable workflow
on:
  push:
    branches:
      - main
    paths:
      - 'react_demo/**'
  workflow_dispatch:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: react_demo/node_modules
          key: cond-flow-deps-${{hashfiles('**/package-lock.json')}}
      - name: Install Dependencies
        if: steps.cache_deps.outputs.cache-hit != 'true'
        run: |
          cd react_demo
          npm ci    
  lint:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: react_demo/node_modules
          key: cond-flow-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_deps.outputs.cache-hit != 'true'
        run: |
          cd react_demo
          npm ci
      - name: Lint code
        run: |
          cd react_demo
          npm run lint
  test:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: react_demo/node_modules
          key: cond-flow-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_deps.outputs.cache-hit != 'true'
        run: |
          cd react_demo
          npm ci
      - name: Test code
        id: run_tests
        run: |
          cd react_demo
          npm run test
      - name: Upload test report
        if: failure() && steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: react_demo/node_modules
          key: cond-flow-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache_deps.outputs.cache-hit != 'true'      
        run: |
          cd react_demo
          npm ci
      - name: Build website
        id: build-website
        run: |
          cd react_demo
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: react_demo/dist
  deploy:
    needs: build
    uses: ./.github/workflows/exercise_reusable.yml
    with:
      artifact-name: dist-files
    secrets:
      some_secret: ${{ secrets.some_secret }}
  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Deployed"
          echo "${{ needs.deploy.outputs.result }}"
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "We have a problem..."
          echo "${{ github }}"

