name: React Project Test
on: 
  push:
    paths:
      - 'react_demo/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      # We don't have to install nodeJS here as the ubuntu-latest runner has it
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd react_demo
          npm ci
      - name: Run Tests
        run: |
          cd react_demo
          npm test
